### ISSUE TITLE
NVVP on EWS

### ISSUE THREAD

**Issue by K-Wu** [illinois-impact/ece408_project#12]
I verified that `module load cuda-toolkit/10` on EWS will allow you to run nvvp from the command line instantly. This saves a lot of trouble installing the functionality.

If it works, maybe you want to modify https://github.com/illinois-impact/ece408_project#nvvp-on-ews accordingly.

**Comment by cwpearson** [comment]
Thanks Kun! Fixed in 9eeb200b1e5dfde5731fbc684fb67d8bd806328a
