### ISSUE TITLE
readme last part bug

### ISSUE THREAD

**Issue by Alexander5421** [illinois-impact/ece408_project#15]
"Skeleton Code Description
custom/cpu-new-forward.cc and custom/new-forward.cu containes skeleton implementations for the **CPU and CPU** convolutions respectively. You can complete the project by modifying these two files only. custom/cpu-new-forward.h and custom/gpu-new-forward.h are the respective header files. You need not modify these files unless you need to declare your own functions.

The code in m2.cc, m3.cc, m4.cc and final.cc are the top level files that are executed for each milestone. You should not be modifying these files."

should be CPU and GPU

**Comment by cwpearson** [comment]
Looks like this is fixed in the master branch, which hasn't been updated in a while. Where are you seeing this?

**Comment by Alexander5421** [comment]
I saw this on 2020fa

**Comment by aschuh703** [comment]
Fixed
